### PR TITLE
feat: edit thread title

### PR DESCRIPTION
**Pull request by decentral1se**
Closes https://github.com/cblgh/cerca/issues/81. Related: https://github.com/cblgh/cerca/pull/89.

I've tried to keep this changeset small. I've tested that other users can't edit threads of other users, the existing 403 handling works.

Open to suggestions on naming and potentially how to bundle the post update into a single statement? Doesn't seem like a biggie but I'm curios if anyone knows how.

image

image

### CODE REVIEW

**Comment by cblgh** [comment]
also lmk if the above way of iterating is way too cumbersome :) just wanted to try something out that is more collaborative than "can you do xx yy zz pls ok thx"

**Comment by decentral1se** [comment]
seems legit!

I had to use `git apply --ignore-space-change --ignore-whitespace ...` to apply it due to their being a mix of space/tabs in the file 😅 I like this approach tho, happy to experiment!

also caught a potential hack scenario where you can edit the title on non-op posts in https://github.com/cblgh/cerca/pull/91/commits/53125af4cf5afd8676d8b3ee4a50b87247d367a6 (does involve a "all posts" query but this can be optimised with a `LIMIT` at some point ala "GetFirstPost?)

**Comment by cblgh** [comment]
> > happy to experiment!
> 
> As a demonstration of my chaotic zeal, I'd even be up for moving the entire development of this forum on to a `cerca` instance itself to dogfood and doing some sort of devilish send-patch machinery for development 😂

ahah yees! :star_struck:  i'll see about setting this up next week!!

**Comment by cblgh** [comment]
btw, i'm ready to merge this! wdyt?

**Comment by decentral1se** [comment]
@cblgh yesssssssssss

**Comment by cblgh** [comment]
:tada: :tada: :tada: nicely done!

**Pull request merged**
